### ISSUE TITLE
Main menu layout planning (on paper).

### ISSUE THREAD

**Issue by edwardyh** [edwardyh/GlobalVRGameJam2015#33]

**Comment by AtelierRadius** [comment]
Wordy explanation: Title screen starts with a view of the tile flooring, a chef cat's shadow is seen with animated tail wagging. After 5 seconds, the game title drops into the scene, logo is some sort of cheese thing.

User must swipe the logo downward in order to access the menu screen which lists options for story+controls, single player and multiplayer modes. Doing so will trigger the cheese logo to be swatted closer to the player. And a mouse appears in the top left corner, animated while user makes next decision. Swipe hand up and down to select from the available choices (some resemblance to Sword Art Online menu interface). Swipe right to select the option.

Selecting the Story+Controls option will trigger the mouse to run away while a recipe page falls on top of the cheese. Recipe outlines the story, controls, and a list of power-ups with explanation as a cat's pawprint covers that region. Swipe left to return to menu screen. Recipe it picked up by cat, and mouse returns to the usual corner.

Selecting either of the game options will have the mouse dash through the screen and run off with cheese logo. The intermediate level selection screen (level difficulty/timed play/etc) is displayed with similar hand gesture selection screen. Insert fancy animations after selection is made Cat makes a loud MEOW! sound as if realizing that the cheese is missing (either before level selection or after level selection). Cat's shadow grows. Game start!

![img_20150708_004414](https://cloud.githubusercontent.com/assets/10199577/8565881/83e1d258-250e-11e5-901b-a01544438451.jpg)
